import type {Evidence,Event,Story} from './types';
const now='2026-07-01T00:00:00.000Z';
export const evidence:Evidence[]=[
{id:'EV-001',eventId:'mobilisation',titleEn:'Institutional background reference',titleBn:'প্রাতিষ্ঠানিক প্রেক্ষাপট সূত্র',summaryEn:'A linked institutional report used as a starting point for contextual research.',summaryBn:'প্রাসঙ্গিক গবেষণার সূচনাবিন্দু হিসেবে ব্যবহৃত একটি সংযুক্ত প্রাতিষ্ঠানিক প্রতিবেদন।',date:'2024-07',locationEn:'Bangladesh',locationBn:'বাংলাদেশ',sourceType:'Institutional report',sourceName:'UN Human Rights Office',sourceUrl:'https://www.ohchr.org/en/documents/country-reports/ohchr-fact-finding-report-human-rights-violations-and-abuses-related',corroboratingSourceIds:['EV-002'],verificationStatus:'Source linked',consentStatus:'Public institutional publication',reuseLicence:'Link and original summary only',submittedByType:'Curated demo',createdAt:now,updatedAt:now,integrityHash:'',demoOnly:true,notesEn:'Demo metadata; consult the original source.',notesBn:'ডেমো মেটাডেটা; মূল উৎস দেখুন।'},
{id:'EV-002',eventId:'scarcity',titleEn:'Preliminary institutional analysis',titleBn:'প্রাথমিক প্রাতিষ্ঠানিক বিশ্লেষণ',summaryEn:'A public preliminary analysis linked for careful comparison with later reporting.',summaryBn:'পরবর্তী প্রতিবেদনের সঙ্গে সতর্ক তুলনার জন্য সংযুক্ত একটি প্রকাশ্য প্রাথমিক বিশ্লেষণ।',date:'2024-07',locationEn:'Bangladesh',locationBn:'বাংলাদেশ',sourceType:'Institutional report',sourceName:'UN Human Rights Office',sourceUrl:'https://www.ohchr.org/en/documents/country-reports/preliminary-analysis-recent-protests-and-unrest-bangladesh',corroboratingSourceIds:['EV-001'],verificationStatus:'Corroborated',consentStatus:'Public institutional publication',reuseLicence:'Link and original summary only',submittedByType:'Curated demo',createdAt:now,updatedAt:now,integrityHash:'',demoOnly:true,notesEn:'Demo metadata; no claim is automatically proven.',notesBn:'ডেমো মেটাডেটা; কোনো দাবি স্বয়ংক্রিয়ভাবে প্রমাণিত নয়।'},
{id:'EV-003',eventId:'scarcity',titleEn:'Internet access advocacy statement',titleBn:'ইন্টারনেট প্রবেশাধিকার বিষয়ক বিবৃতি',summaryEn:'A civil-society statement concerning internet access during the period.',summaryBn:'এই সময়ের ইন্টারনেট প্রবেশাধিকার সম্পর্কিত একটি নাগরিক সমাজের বিবৃতি।',date:'2024-07',locationEn:'Bangladesh',locationBn:'বাংলাদেশ',sourceType:'Public statement',sourceName:'Access Now',sourceUrl:'https://www.accessnow.org/press-release/keepiton-restore-internet-during-student-protests-bangladesh/',corroboratingSourceIds:[],verificationStatus:'Source linked',consentStatus:'Public statement',reuseLicence:'Link and original summary only',submittedByType:'Curated demo',createdAt:now,updatedAt:now,integrityHash:'',demoOnly:true,notesEn:'Read the linked statement in its original context.',notesBn:'সংযুক্ত বিবৃতিটি মূল প্রেক্ষাপটে পড়ুন।'}];
export const events:Event[]=[
['mobilisation','Early student mobilisation','প্রাথমিক শিক্ষার্থী সংগঠিত হওয়া','Students began organising and expressing concerns in public spaces.','শিক্ষার্থীরা জনপরিসরে সংগঠিত হয়ে উদ্বেগ প্রকাশ করতে শুরু করে।','Early July 2024','Civic participation'],
['concern','Escalating public concern','বাড়তে থাকা জনউদ্বেগ','Public attention widened as accounts and documentation circulated.','বিভিন্ন বিবরণ ও নথি ছড়িয়ে পড়লে জনমনোযোগ বিস্তৃত হয়।','Mid July 2024','Public concern'],
['scarcity','Communication disruption and information scarcity','যোগাযোগ বিঘ্ন ও তথ্যের সংকট','Restricted communication made preservation and contextual verification harder.','যোগাযোগ সীমিত হওয়ায় সংরক্ষণ ও প্রেক্ষাপট যাচাই কঠিন হয়ে ওঠে।','Mid–late July 2024','Information access'],
['participation','Nationwide civic participation','দেশব্যাপী নাগরিক অংশগ্রহণ','Participation expanded across communities and multiple locations.','বিভিন্ন জনগোষ্ঠী ও স্থানে অংশগ্রহণ বিস্তৃত হয়।','July 2024','Civic participation'],
['solidarity','Public solidarity and mutual support','জনসংহতি ও পারস্পরিক সহায়তা','People developed forms of solidarity, care, and mutual support.','মানুষ সংহতি, যত্ন ও পারস্পরিক সহায়তার নানা উদ্যোগ গড়ে তোলে।','July 2024','Solidarity'],
['remembrance','Preservation, accountability, and remembrance','সংরক্ষণ, জবাবদিহি ও স্মরণ','Attention turned toward preserving records and learning responsibly.','নথি সংরক্ষণ ও দায়িত্বশীলভাবে শেখার দিকে মনোযোগ যায়।','2024–present','Remembrance']
].map((x,i)=>({id:x[0],title:{en:x[1],bn:x[2]},summary:{en:x[3],bn:x[4]},date:x[5],location:{en:'Multiple locations',bn:'একাধিক স্থান'},category:x[6],status:i===2?'Corroborated':'Archived demonstration',evidenceIds:i===0?['EV-001']:i===2?['EV-002','EV-003']:[],storyId:['first-signals','information-gap','living-memory'][i%3],sourceCount:i===2?2:i===0?1:0,demoOnly:true} as Event));
export const stories:Story[]=[
{id:'first-signals',title:{en:'The first signals',bn:'প্রথম সংকেত'},dek:{en:'How civic concern moved from conversation into shared public memory.',bn:'নাগরিক উদ্বেগ কীভাবে কথোপকথন থেকে যৌথ জনস্মৃতিতে রূপ নেয়।'},context:{en:'This composite demonstration narrative describes broad patterns without identifying individuals.',bn:'এই সমন্বিত প্রদর্শনী বয়ান ব্যক্তিকে শনাক্ত না করে বিস্তৃত ধারা তুলে ধরে।'},moments:[{en:'Questions moved from private conversations into public spaces.',bn:'প্রশ্ন ব্যক্তিগত আলাপ থেকে জনপরিসরে আসে।'},{en:'People began saving links and records.',bn:'মানুষ লিংক ও নথি সংরক্ষণ শুরু করে।'}],known:{en:'Public records show a period of mobilisation and widening concern.',bn:'প্রকাশ্য নথিতে সংগঠিত হওয়া ও উদ্বেগ বিস্তারের একটি সময় দেখা যায়।'},uncertain:{en:'Many individual accounts still require consent, context, and corroboration.',bn:'অনেক ব্যক্তিগত বিবরণে এখনো সম্মতি, প্রেক্ষাপট ও সমর্থনকারী সূত্র প্রয়োজন।'},matters:{en:'Preservation keeps later study connected to traceable sources.',bn:'সংরক্ষণ পরবর্তী অধ্যয়নকে অনুসরণযোগ্য উৎসের সঙ্গে যুক্ত রাখে।'},reflection:{en:'What should a responsible public memory protect?',bn:'একটি দায়িত্বশীল জনস্মৃতির কী রক্ষা করা উচিত?'},evidenceIds:['EV-001'],composite:true},
{id:'information-gap',title:{en:'When the signal faded',bn:'যখন সংযোগ ক্ষীণ হলো'},dek:{en:'Information scarcity made context, safety, and verification more difficult.',bn:'তথ্যের সংকট প্রেক্ষাপট, নিরাপত্তা ও যাচাইকে আরও কঠিন করে তোলে।'},context:{en:'This story examines documentation challenges rather than making claims about a single incident.',bn:'এই গল্প একক ঘটনা নিয়ে দাবি না করে নথিবদ্ধ করার চ্যালেঞ্জ বিশ্লেষণ করে।'},moments:[{en:'Access to timely information became uneven.',bn:'সময়মতো তথ্য পাওয়ার সুযোগ অসম হয়ে পড়ে।'},{en:'Copies moved between devices and lost context.',bn:'কপি ডিভাইসে ডিভাইসে ঘুরে প্রেক্ষাপট হারায়।'}],known:{en:'Linked public sources discuss communication access during the period.',bn:'সংযুক্ত প্রকাশ্য সূত্রগুলো এ সময়ের যোগাযোগ প্রবেশাধিকার নিয়ে আলোচনা করে।'},uncertain:{en:'A file’s origin and editing history may be unclear.',bn:'কোনো ফাইলের উৎস ও সম্পাদনার ইতিহাস অস্পষ্ট হতে পারে।'},matters:{en:'A source trail helps future readers distinguish records from reposts.',bn:'উৎসের ধারাবাহিকতা ভবিষ্যৎ পাঠককে মূল নথি ও পুনঃপ্রকাশ আলাদা করতে সাহায্য করে।'},reflection:{en:'What context would you need before sharing a record?',bn:'কোনো নথি শেয়ার করার আগে আপনার কী প্রেক্ষাপট দরকার?'},evidenceIds:['EV-002','EV-003'],composite:true},
{id:'living-memory',title:{en:'A living archive',bn:'জীবন্ত আর্কাইভ'},dek:{en:'Preservation is a continuing civic practice, not a finished collection.',bn:'সংরক্ষণ কোনো সমাপ্ত সংগ্রহ নয়, এটি চলমান নাগরিক চর্চা।'},context:{en:'Small, portable collections can complement responsible institutional archives.',bn:'ছোট বহনযোগ্য সংগ্রহ দায়িত্বশীল প্রাতিষ্ঠানিক আর্কাইভের পরিপূরক হতে পারে।'},moments:[{en:'Records are described, linked, and fingerprinted.',bn:'নথি বর্ণনা, সংযোগ ও ফিঙ্গারপ্রিন্ট করা হয়।'},{en:'Uncertainty stays visible beside what is documented.',bn:'যা নথিবদ্ধ তার পাশে অনিশ্চয়তাও দৃশ্যমান থাকে।'}],known:{en:'Integrity checks can detect later record changes.',bn:'ইন্টেগ্রিটি যাচাই পরবর্তী পরিবর্তন শনাক্ত করতে পারে।'},uncertain:{en:'Integrity does not establish factual truth.',bn:'ইন্টেগ্রিটি বাস্তব সত্য প্রতিষ্ঠা করে না।'},matters:{en:'Transparent limits make archives more trustworthy and useful.',bn:'স্বচ্ছ সীমাবদ্ধতা আর্কাইভকে আরও বিশ্বাসযোগ্য ও উপযোগী করে।'},reflection:{en:'How can an archive preserve dignity as well as data?',bn:'একটি আর্কাইভ কীভাবে তথ্যের পাশাপাশি মর্যাদাও রক্ষা করতে পারে?'},evidenceIds:['EV-001','EV-002'],composite:true}
];
